In [5]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [7]:
df = pd.read_csv("../dataset/heart_statlog_cleveland_hungary_final.csv")

df.head()

,age,sex,chest pain type,resting bp s,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,40,1,2,140,289,0,0,172,0,0.0,1,0
1,49,0,3,160,180,0,0,156,0,1.0,2,1
2,37,1,2,130,283,0,1,98,0,0.0,1,0
3,48,0,4,138,214,0,0,108,1,1.5,2,1
4,54,1,3,150,195,0,0,122,0,0.0,1,0

In [8]:
X = df.drop("target", axis=1)

y = df["target"]

print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

Features Shape : (1190, 11)
Target Shape : (1190,)

In [9]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 272

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [11]:
print("Training Features :", X_train.shape)
print("Testing Features :", X_test.shape)

print("Training Target :", y_train.shape)
print("Testing Target :", y_test.shape)

Training Features : (952, 11)
Testing Features : (238, 11)
Training Target : (952,)
Testing Target : (238,)

In [12]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [13]:
print(X_train_scaled[:5])

[[-0.0947197   0.56764621 -0.23856642 -1.47235956 -2.13694316 -0.50753894
  -0.81250594 -0.97555336 -0.79733232 -0.87297171  0.60477172]
 [-1.37075492  0.56764621 -1.30483509  0.14161868 -0.09965282 -0.50753894
  -0.81250594 -0.30692356 -0.79733232 -0.87297171  0.60477172]
 [-0.20105597 -1.76166066  0.82770226 -0.12737769 -0.33047882 -0.50753894
  -0.81250594  0.00772576  1.25418219  0.50631973  0.60477172]
 [ 0.75597044  0.56764621 -1.30483509  0.35681578  0.70322022 -0.50753894
  -0.81250594 -0.18893006 -0.79733232 -0.59711342 -1.03086088]
 [-1.58342745  0.56764621 -0.23856642  0.41061505  1.08458491 -0.50753894
   1.48276306  1.6596347  -0.79733232 -0.87297171 -1.03086088]]

In [14]:
import joblib

joblib.dump(scaler, "../model/scaler.pkl")

print("Scaler saved successfully!")

Scaler saved successfully!

In [15]:
duplicates = df[df.duplicated()]
duplicates.head(10)

,age,sex,chest pain type,resting bp s,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
163,49,0,2,110,208,0,0,160,0,0.0,1,0
604,58,1,3,150,219,0,1,118,1,0.0,2,1
887,63,1,1,145,233,1,2,150,0,2.3,3,0
888,67,1,4,160,286,0,2,108,1,1.5,2,1
889,67,1,4,120,229,0,2,129,1,2.6,2,1
890,37,1,3,130,250,0,0,187,0,3.5,3,0
891,41,0,2,130,204,0,2,172,0,1.4,1,0
892,56,1,2,120,236,0,0,178,0,0.8,1,0
893,62,0,4,140,268,0,2,160,0,3.6,3,1
894,57,0,4,120,354,0,0,163,1,0.6,1,0

In [16]:
duplicates.shape

(272, 12)

In [17]:
print("Dataset Shape Before:", df.shape)

df = df.drop_duplicates()

print("Dataset Shape After :", df.shape)

Dataset Shape Before: (1190, 12)
Dataset Shape After : (918, 12)

In [18]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [19]:
X = df.drop("target", axis=1)
y = df["target"]

print(X.shape)
print(y.shape)

(918, 11)
(918,)

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [21]:



from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [22]:
import joblib

joblib.dump(scaler, "../model/scaler.pkl")

print("Updated scaler saved successfully!")

Updated scaler saved successfully!

In [23]:


import pandas as pd
import joblib

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    cohen_kappa_score,
    confusion_matrix,
    classification_report
)

In [24]:
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    cohen_kappa_score
)

In [25]:
lr_model = LogisticRegression(random_state=42)

lr_model.fit(X_train_scaled, y_train)

LogisticRegression(random_state=42)

In [26]:
y_pred = lr_model.predict(X_test_scaled)

y_prob = lr_model.predict_proba(X_test_scaled)[:,1]

In [27]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)
kappa = cohen_kappa_score(y_test, y_pred)

In [28]:
print("="*50)
print("Logistic Regression Results")
print("="*50)

print(f"Accuracy      : {accuracy:.4f}")
print(f"Precision     : {precision:.4f}")
print(f"Recall        : {recall:.4f}")
print(f"F1 Score      : {f1:.4f}")
print(f"ROC-AUC Score : {auc:.4f}")
print(f"Cohen Kappa   : {kappa:.4f}")

==================================================
Logistic Regression Results
==================================================
Accuracy      : 0.8859
Precision     : 0.8716
Recall        : 0.9314
F1 Score      : 0.9005
ROC-AUC Score : 0.9014
Cohen Kappa   : 0.7671

In [29]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[68 14]
 [ 7 95]]

In [30]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.83      0.87        82
           1       0.87      0.93      0.90       102

    accuracy                           0.89       184
   macro avg       0.89      0.88      0.88       184
weighted avg       0.89      0.89      0.89       184

In [31]:
import joblib

joblib.dump(lr_model, "../model/logistic_regression.pkl")

print("Logistic Regression Model Saved Successfully!")

Logistic Regression Model Saved Successfully!

In [32]:
from sklearn.tree import DecisionTreeClassifier

In [33]:
dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [34]:
y_pred_dt = dt_model.predict(X_test)

y_prob_dt = dt_model.predict_proba(X_test)[:, 1]

In [35]:
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt)
recall_dt = recall_score(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)
auc_dt = roc_auc_score(y_test, y_prob_dt)
kappa_dt = cohen_kappa_score(y_test, y_pred_dt)

In [36]:

print("=" * 50)
print("Decision Tree Results")
print("=" * 50)

print(f"Accuracy      : {accuracy_dt:.4f}")
print(f"Precision     : {precision_dt:.4f}")
print(f"Recall        : {recall_dt:.4f}")
print(f"F1 Score      : {f1_dt:.4f}")
print(f"ROC-AUC Score : {auc_dt:.4f}")
print(f"Cohen Kappa   : {kappa_dt:.4f}")

==================================================
Decision Tree Results
==================================================
Accuracy      : 0.7772
Precision     : 0.7850
Recall        : 0.8235
F1 Score      : 0.8038
ROC-AUC Score : 0.7715
Cohen Kappa   : 0.5463

In [37]:
cm_dt = confusion_matrix(y_test, y_pred_dt)
print(cm_dt)

[[59 23]
 [18 84]]

In [38]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.77      0.72      0.74        82
           1       0.79      0.82      0.80       102

    accuracy                           0.78       184
   macro avg       0.78      0.77      0.77       184
weighted avg       0.78      0.78      0.78       184

In [39]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)
y_prob_rf = rf_model.predict_proba(X_test)[:,1]

In [40]:
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)
auc_rf = roc_auc_score(y_test, y_prob_rf)
kappa_rf = cohen_kappa_score(y_test, y_pred_rf)

print("="*50)
print("Random Forest Results")
print("="*50)
print(f"Accuracy      : {accuracy_rf:.4f}")
print(f"Precision     : {precision_rf:.4f}")
print(f"Recall        : {recall_rf:.4f}")
print(f"F1 Score      : {f1_rf:.4f}")
print(f"ROC-AUC Score : {auc_rf:.4f}")
print(f"Cohen Kappa   : {kappa_rf:.4f}")

cm_rf = confusion_matrix(y_test, y_pred_rf)
print(cm_rf)

print(classification_report(y_test, y_pred_rf))

==================================================
Random Forest Results
==================================================
Accuracy      : 0.8804
Precision     : 0.8774
Recall        : 0.9118
F1 Score      : 0.8942
ROC-AUC Score : 0.9325
Cohen Kappa   : 0.7568
[[69 13]
 [ 9 93]]
              precision    recall  f1-score   support

           0       0.88      0.84      0.86        82
           1       0.88      0.91      0.89       102

    accuracy                           0.88       184
   macro avg       0.88      0.88      0.88       184
weighted avg       0.88      0.88      0.88       184

In [41]:
# ============================
# K-Nearest Neighbors (KNN)
# ============================

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    cohen_kappa_score,
    confusion_matrix,
    classification_report
)
import joblib

# Train the model
knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred_knn = knn_model.predict(X_test_scaled)
y_prob_knn = knn_model.predict_proba(X_test_scaled)[:, 1]

# Calculate evaluation metrics
accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn)
recall_knn = recall_score(y_test, y_pred_knn)
f1_knn = f1_score(y_test, y_pred_knn)
auc_knn = roc_auc_score(y_test, y_prob_knn)
kappa_knn = cohen_kappa_score(y_test, y_pred_knn)

# Display results
print("=" * 50)
print("K-Nearest Neighbors (KNN) Results")
print("=" * 50)

print(f"Accuracy      : {accuracy_knn:.4f}")
print(f"Precision     : {precision_knn:.4f}")
print(f"Recall        : {recall_knn:.4f}")
print(f"F1 Score      : {f1_knn:.4f}")
print(f"ROC-AUC Score : {auc_knn:.4f}")
print(f"Cohen Kappa   : {kappa_knn:.4f}")

# Confusion Matrix
cm_knn = confusion_matrix(y_test, y_pred_knn)

print("\nConfusion Matrix")
print(cm_knn)

# Classification Report
print("\nClassification Report")
print(classification_report(y_test, y_pred_knn))

# Save the model
joblib.dump(knn_model, "../model/knn_model.pkl")

print("\nKNN Model Saved Successfully!")

==================================================
K-Nearest Neighbors (KNN) Results
==================================================
Accuracy      : 0.8913
Precision     : 0.8796
Recall        : 0.9314
F1 Score      : 0.9048
ROC-AUC Score : 0.9204
Cohen Kappa   : 0.7784

Confusion Matrix
[[69 13]
 [ 7 95]]

Classification Report
              precision    recall  f1-score   support

           0       0.91      0.84      0.87        82
           1       0.88      0.93      0.90       102

    accuracy                           0.89       184
   macro avg       0.89      0.89      0.89       184
weighted avg       0.89      0.89      0.89       184


KNN Model Saved Successfully!

In [42]:
# ============================
# AdaBoost Classifier
# ============================

from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    cohen_kappa_score,
    confusion_matrix,
    classification_report
)
import joblib

# Train the model
ada_model = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)

ada_model.fit(X_train, y_train)

# Make predictions
y_pred_ada = ada_model.predict(X_test)
y_prob_ada = ada_model.predict_proba(X_test)[:, 1]

# Calculate evaluation metrics
accuracy_ada = accuracy_score(y_test, y_pred_ada)
precision_ada = precision_score(y_test, y_pred_ada)
recall_ada = recall_score(y_test, y_pred_ada)
f1_ada = f1_score(y_test, y_pred_ada)
auc_ada = roc_auc_score(y_test, y_prob_ada)
kappa_ada = cohen_kappa_score(y_test, y_pred_ada)

# Display results
print("=" * 50)
print("AdaBoost Results")
print("=" * 50)

print(f"Accuracy      : {accuracy_ada:.4f}")
print(f"Precision     : {precision_ada:.4f}")
print(f"Recall        : {recall_ada:.4f}")
print(f"F1 Score      : {f1_ada:.4f}")
print(f"ROC-AUC Score : {auc_ada:.4f}")
print(f"Cohen Kappa   : {kappa_ada:.4f}")

# Confusion Matrix
cm_ada = confusion_matrix(y_test, y_pred_ada)

print("\nConfusion Matrix")
print(cm_ada)

# Classification Report
print("\nClassification Report")
print(classification_report(y_test, y_pred_ada))

# Save the model
joblib.dump(ada_model, "../model/adaboost_model.pkl")

print("\nAdaBoost Model Saved Successfully!")

==================================================
AdaBoost Results
==================================================
Accuracy      : 0.8859
Precision     : 0.9010
Recall        : 0.8922
F1 Score      : 0.8966
ROC-AUC Score : 0.9199
Cohen Kappa   : 0.7693

Confusion Matrix
[[72 10]
 [11 91]]

Classification Report
              precision    recall  f1-score   support

           0       0.87      0.88      0.87        82
           1       0.90      0.89      0.90       102

    accuracy                           0.89       184
   macro avg       0.88      0.89      0.88       184
weighted avg       0.89      0.89      0.89       184


AdaBoost Model Saved Successfully!

In [43]:
import pandas as pd

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "KNN",
        "AdaBoost"
    ],
    "Accuracy": [
        accuracy,
        accuracy_dt,
        accuracy_rf,
        accuracy_knn,
        accuracy_ada
    ],
    "Precision": [
        precision,
        precision_dt,
        precision_rf,
        precision_knn,
        precision_ada
    ],
    "Recall": [
        recall,
        recall_dt,
        recall_rf,
        recall_knn,
        recall_ada
    ],
    "F1 Score": [
        f1,
        f1_dt,
        f1_rf,
        f1_knn,
        f1_ada
    ],
    "ROC-AUC": [
        auc,
        auc_dt,
        auc_rf,
        auc_knn,
        auc_ada
    ],
    "Cohen Kappa": [
        kappa,
        kappa_dt,
        kappa_rf,
        kappa_knn,
        kappa_ada
    ]
})

results = results.sort_values(by="Accuracy", ascending=False)

results

,Model,Accuracy,Precision,Recall,F1 Score,ROC-AUC,Cohen Kappa
3,KNN,0.891304,0.879630,0.931373,0.904762,0.920373,0.778420
0,Logistic Regression,0.885870,0.871560,0.931373,0.900474,0.901363,0.767061
4,AdaBoost,0.885870,0.900990,0.892157,0.896552,0.919895,0.769286
2,Random Forest,0.880435,0.877358,0.911765,0.894231,0.932508,0.756848
1,Decision Tree,0.777174,0.785047,0.823529,0.803828,0.771521,0.546307

In [44]:
# ==========================================
# Hybrid Model 1 : KNN + Random Forest
# ==========================================

from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    cohen_kappa_score,
    confusion_matrix,
    classification_report
)
import joblib

knn = KNeighborsClassifier(n_neighbors=5)

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

ensemble_knn_rf = VotingClassifier(
    estimators=[
        ("knn", knn),
        ("rf", rf)
    ],
    voting="soft"
)

# Train
ensemble_knn_rf.fit(X_train_scaled, y_train)

# Predict
y_pred = ensemble_knn_rf.predict(X_test_scaled)
y_prob = ensemble_knn_rf.predict_proba(X_test_scaled)[:, 1]

# Metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)
kappa = cohen_kappa_score(y_test, y_pred)

print("=" * 50)
print("Hybrid KNN + RF Results")
print("=" * 50)

print(f"Accuracy      : {accuracy:.4f}")
print(f"Precision     : {precision:.4f}")
print(f"Recall        : {recall:.4f}")
print(f"F1 Score      : {f1:.4f}")
print(f"ROC-AUC Score : {auc:.4f}")
print(f"Cohen Kappa   : {kappa:.4f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

joblib.dump(ensemble_knn_rf, "../model/knn_rf_ensemble.pkl")

print("\nHybrid Model Saved Successfully!")

==================================================
Hybrid KNN + RF Results
==================================================
Accuracy      : 0.9130
Precision     : 0.9135
Recall        : 0.9314
F1 Score      : 0.9223
ROC-AUC Score : 0.9396
Cohen Kappa   : 0.8236

Confusion Matrix
[[73  9]
 [ 7 95]]

Classification Report
              precision    recall  f1-score   support

           0       0.91      0.89      0.90        82
           1       0.91      0.93      0.92       102

    accuracy                           0.91       184
   macro avg       0.91      0.91      0.91       184
weighted avg       0.91      0.91      0.91       184


Hybrid Model Saved Successfully!

In [45]:
# ==========================================
# Hybrid Model 2 : Logistic Regression + Random Forest
# ==========================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    cohen_kappa_score,
    confusion_matrix,
    classification_report
)
import joblib

# Base Models
lr = LogisticRegression(random_state=42)

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

# Hybrid Model
ensemble_lr_rf = VotingClassifier(
    estimators=[
        ("lr", lr),
        ("rf", rf)
    ],
    voting="soft"
)

# Train
ensemble_lr_rf.fit(X_train_scaled, y_train)

# Predict
y_pred_lr_rf = ensemble_lr_rf.predict(X_test_scaled)
y_prob_lr_rf = ensemble_lr_rf.predict_proba(X_test_scaled)[:,1]

# Metrics
accuracy_lr_rf = accuracy_score(y_test, y_pred_lr_rf)
precision_lr_rf = precision_score(y_test, y_pred_lr_rf)
recall_lr_rf = recall_score(y_test, y_pred_lr_rf)
f1_lr_rf = f1_score(y_test, y_pred_lr_rf)
auc_lr_rf = roc_auc_score(y_test, y_prob_lr_rf)
kappa_lr_rf = cohen_kappa_score(y_test, y_pred_lr_rf)

print("="*50)
print("Hybrid Logistic Regression + RF Results")
print("="*50)

print(f"Accuracy      : {accuracy_lr_rf:.4f}")
print(f"Precision     : {precision_lr_rf:.4f}")
print(f"Recall        : {recall_lr_rf:.4f}")
print(f"F1 Score      : {f1_lr_rf:.4f}")
print(f"ROC-AUC Score : {auc_lr_rf:.4f}")
print(f"Cohen Kappa   : {kappa_lr_rf:.4f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_lr_rf))

print("\nClassification Report")
print(classification_report(y_test, y_pred_lr_rf))

joblib.dump(ensemble_lr_rf, "../model/lr_rf_ensemble.pkl")

print("\nHybrid LR + RF Model Saved Successfully!")

==================================================
Hybrid Logistic Regression + RF Results
==================================================
Accuracy      : 0.8967
Precision     : 0.8807
Recall        : 0.9412
F1 Score      : 0.9100
ROC-AUC Score : 0.9290
Cohen Kappa   : 0.7892

Confusion Matrix
[[69 13]
 [ 6 96]]

Classification Report
              precision    recall  f1-score   support

           0       0.92      0.84      0.88        82
           1       0.88      0.94      0.91       102

    accuracy                           0.90       184
   macro avg       0.90      0.89      0.89       184
weighted avg       0.90      0.90      0.90       184


Hybrid LR + RF Model Saved Successfully!

In [48]:
# ==========================================
# Hybrid Model 3 : Decision Tree + Random Forest
# ==========================================

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    cohen_kappa_score,
    confusion_matrix,
    classification_report
)
import joblib

# Base Models
dt = DecisionTreeClassifier(random_state=42)

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

# Hybrid Model
ensemble_dt_rf = VotingClassifier(
    estimators=[
        ("dt", dt),
        ("rf", rf)
    ],
    voting="soft"
)

# Train
ensemble_dt_rf.fit(X_train, y_train)

# Predict
y_pred_dt_rf = ensemble_dt_rf.predict(X_test)
y_prob_dt_rf = ensemble_dt_rf.predict_proba(X_test)[:,1]

# Evaluation
accuracy_dt_rf = accuracy_score(y_test, y_pred_dt_rf)
precision_dt_rf = precision_score(y_test, y_pred_dt_rf)
recall_dt_rf = recall_score(y_test, y_pred_dt_rf)
f1_dt_rf = f1_score(y_test, y_pred_dt_rf)
auc_dt_rf = roc_auc_score(y_test, y_prob_dt_rf)
kappa_dt_rf = cohen_kappa_score(y_test, y_pred_dt_rf)

print("="*50)
print("Hybrid Decision Tree + RF Results")
print("="*50)

print(f"Accuracy      : {accuracy_dt_rf:.4f}")
print(f"Precision     : {precision_dt_rf:.4f}")
print(f"Recall        : {recall_dt_rf:.4f}")
print(f"F1 Score      : {f1_dt_rf:.4f}")
print(f"ROC-AUC Score : {auc_dt_rf:.4f}")
print(f"Cohen Kappa   : {kappa_dt_rf:.4f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_dt_rf))

print("\nClassification Report")
print(classification_report(y_test, y_pred_dt_rf))

joblib.dump(ensemble_dt_rf, "../model/dt_rf_ensemble.pkl")

print("\nHybrid DT + RF Model Saved Successfully!")

==================================================
Hybrid Decision Tree + RF Results
==================================================
Accuracy      : 0.7772
Precision     : 0.7850
Recall        : 0.8235
F1 Score      : 0.8038
ROC-AUC Score : 0.9054
Cohen Kappa   : 0.5463

Confusion Matrix
[[59 23]
 [18 84]]

Classification Report
              precision    recall  f1-score   support

           0       0.77      0.72      0.74        82
           1       0.79      0.82      0.80       102

    accuracy                           0.78       184
   macro avg       0.78      0.77      0.77       184
weighted avg       0.78      0.78      0.78       184


Hybrid DT + RF Model Saved Successfully!

In [49]:
# ==========================================
# Hybrid Model 4 : AdaBoost + Random Forest
# ==========================================

from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier, VotingClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    cohen_kappa_score,
    confusion_matrix,
    classification_report
)
import joblib

# Base Models
ada = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

# Hybrid Model
ensemble_ada_rf = VotingClassifier(
    estimators=[
        ("ada", ada),
        ("rf", rf)
    ],
    voting="soft"
)

# Train
ensemble_ada_rf.fit(X_train, y_train)

# Predict
y_pred_ada_rf = ensemble_ada_rf.predict(X_test)
y_prob_ada_rf = ensemble_ada_rf.predict_proba(X_test)[:,1]

# Evaluation
accuracy_ada_rf = accuracy_score(y_test, y_pred_ada_rf)
precision_ada_rf = precision_score(y_test, y_pred_ada_rf)
recall_ada_rf = recall_score(y_test, y_pred_ada_rf)
f1_ada_rf = f1_score(y_test, y_pred_ada_rf)
auc_ada_rf = roc_auc_score(y_test, y_prob_ada_rf)
kappa_ada_rf = cohen_kappa_score(y_test, y_pred_ada_rf)

print("="*50)
print("Hybrid AdaBoost + RF Results")
print("="*50)

print(f"Accuracy      : {accuracy_ada_rf:.4f}")
print(f"Precision     : {precision_ada_rf:.4f}")
print(f"Recall        : {recall_ada_rf:.4f}")
print(f"F1 Score      : {f1_ada_rf:.4f}")
print(f"ROC-AUC Score : {auc_ada_rf:.4f}")
print(f"Cohen Kappa   : {kappa_ada_rf:.4f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_ada_rf))

print("\nClassification Report")
print(classification_report(y_test, y_pred_ada_rf))

joblib.dump(ensemble_ada_rf, "../model/ada_rf_ensemble.pkl")

print("\nHybrid AdaBoost + RF Model Saved Successfully!")

==================================================
Hybrid AdaBoost + RF Results
==================================================
Accuracy      : 0.9076
Precision     : 0.9126
Recall        : 0.9216
F1 Score      : 0.9171
ROC-AUC Score : 0.9322
Cohen Kappa   : 0.8128

Confusion Matrix
[[73  9]
 [ 8 94]]

Classification Report
              precision    recall  f1-score   support

           0       0.90      0.89      0.90        82
           1       0.91      0.92      0.92       102

    accuracy                           0.91       184
   macro avg       0.91      0.91      0.91       184
weighted avg       0.91      0.91      0.91       184


Hybrid AdaBoost + RF Model Saved Successfully!

In [50]:
import joblib

joblib.dump(rf_model, "../model/random_forest.pkl")

print("Random Forest Model Saved Successfully!")

Random Forest Model Saved Successfully!

In [51]:
import joblib

joblib.dump(dt_model, "../model/decision_tree.pkl")

print("Decision Tree Model Saved Successfully!")

Decision Tree Model Saved Successfully!

In [52]:
import joblib

joblib.dump(ensemble_knn_rf, "../model/final_model.pkl")

print("Final Model Saved Successfully!")

Final Model Saved Successfully!